//------------------------------------------------------------------------------ 
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated> 
//-----------------------------------------------------------------------------
 
namespace System.Windows.Controlsb1 {
    using System;
 

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc. 
    /// </summary> 
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio. 
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")] 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource { 
 
        private static global::System.Resources.ResourceManager resourceMan;
 
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] 
        internal Resource() {
        }
 
        /// <summary> 
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary> 
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get { 
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Resource", typeof(Resource).Assembly);
                    resourceMan = temp; 
                } 
                return resourceMan;
            } 
        }

        /// <summary> 
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary> 
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] 
        internal static global::System.Globalization.CultureInfo Culture {
            get { 
                return resourceCulture;
            }
            set { 
                resourceCulture = value;
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot add frozen column.. 
        /// </summary>
        internal static string DataGrid_CannotAddFrozenColumn {
            get { 
                return ResourceManager.GetString("DataGrid_CannotAddFrozenColumn", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot add non-frozen column.. 
        /// </summary>
        internal static string DataGrid_CannotAddNonFrozenColumn {
            get { 
                return ResourceManager.GetString("DataGrid_CannotAddNonFrozenColumn", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot change column collection while adjusting display indexes.. 
        /// </summary>
        internal static string DataGrid_CannotChangeColumnCollectionWhileAdjustingDisplayIndexes {
            get { 
                return ResourceManager.GetString("DataGrid_CannotChangeColumnCollectionWhileAdjustingDisplayIndexes", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot move frozen column.. 
        /// </summary>
        internal static string DataGrid_CannotMoveFrozenColumn {
            get { 
                return ResourceManager.GetString("DataGrid_CannotMoveFrozenColumn", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot move non-frozen column.. 
        /// </summary>
        internal static string DataGrid_CannotMoveNonFrozenColumn {
            get { 
                return ResourceManager.GetString("DataGrid_CannotMoveNonFrozenColumn", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Column cannot be collapsed.. 
        /// </summary>
        internal static string DataGrid_ColumnCannotBeCollapsed {
            get { 
                return ResourceManager.GetString("DataGrid_ColumnCannotBeCollapsed", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Column already belongs to a DataGrid instance and cannot be reassigned.. 
        /// </summary>
        internal static string DataGrid_ColumnCannotBeReassignedToDifferentDataGrid {
            get { 
                return ResourceManager.GetString("DataGrid_ColumnCannotBeReassignedToDifferentDataGrid", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Provided column does not belong to this DataGrid.. 
        /// </summary>
        internal static string DataGrid_ColumnNotInThisDataGrid {
            get { 
                return ResourceManager.GetString("DataGrid_ColumnNotInThisDataGrid", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Commit failed.  Cannot complete operation.. 
        /// </summary>
        internal static string DataGrid_CommitFailedCannotCompleteOperation {
            get { 
                return ResourceManager.GetString("DataGrid_CommitFailedCannotCompleteOperation", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is not a valid &quot;{1}&quot; enumeration value.. 
        /// </summary>
        internal static string DataGrid_InvalidEnumValue {
            get { 
                return ResourceManager.GetString("DataGrid_InvalidEnumValue", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Invalid element, check that the element is contained in a row, and that the row is displayed or selected.. 
        /// </summary>
        internal static string DataGrid_InvalidRowElement {
            get { 
                return ResourceManager.GetString("DataGrid_InvalidRowElement", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to The item is not contained in the ItemsSource.. 
        /// </summary>
        internal static string DataGrid_ItemIsNotContainedInTheItemsSource {
            get { 
                return ResourceManager.GetString("DataGrid_ItemIsNotContainedInTheItemsSource", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to The ItemsSource is null.  Cannot complete operation.. 
        /// </summary>
        internal static string DataGrid_ItemsSourceNullCannotCompleteOperation {
            get { 
                return ResourceManager.GetString("DataGrid_ItemsSourceNullCannotCompleteOperation", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Missing template.  Cannot initialize {0}.. 
        /// </summary>
        internal static string DataGrid_MissingTemplateForType {
            get { 
                return ResourceManager.GetString("DataGrid_MissingTemplateForType", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to There is no current row.  Operation cannot be completed.. 
        /// </summary>
        internal static string DataGrid_NoCurrentRow {
            get { 
                return ResourceManager.GetString("DataGrid_NoCurrentRow", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to There is no instance of DataGrid assigned to this {0}.  Cannot complete operation.. 
        /// </summary>
        internal static string DataGrid_NoOwningGrid {
            get { 
                return ResourceManager.GetString("DataGrid_NoOwningGrid", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a column to read/write when the underlying property does not allow it.. 
        /// </summary>
        internal static string DataGrid_UnderlyingPropertyIsReadOnly {
            get { 
                return ResourceManager.GetString("DataGrid_UnderlyingPropertyIsReadOnly", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set to a null value.. 
        /// </summary>
        internal static string DataGrid_ValueCannotBeSetToNull {
            get { 
                return ResourceManager.GetString("DataGrid_ValueCannotBeSetToNull", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to The value is not an instance of {0}.. 
        /// </summary>
        internal static string DataGrid_ValueIsNotAnInstanceOf {
            get { 
                return ResourceManager.GetString("DataGrid_ValueIsNotAnInstanceOf", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to The value is not an instance of {0} or {1}.. 
        /// </summary>
        internal static string DataGrid_ValueIsNotAnInstanceOfEitherOr {
            get { 
                return ResourceManager.GetString("DataGrid_ValueIsNotAnInstanceOfEitherOr", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} is a read-only value and cannot be reassigned.. 
        /// </summary>
        internal static string DataGrid_ValueIsReadOnly {
            get { 
                return ResourceManager.GetString("DataGrid_ValueIsReadOnly", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeGreaterThan {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeGreaterThan", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeGreaterThanOrEqualTo {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1} and less than {2}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeGTandLT {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeGTandLT", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1} and less than or equal to {2}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeGTandLTE {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeGTandLTE", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1} and less than {2}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeGTEandLT {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeGTEandLT", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1} and less than or equal to {2}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeGTEandLTE {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeGTEandLTE", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeLessThan {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeLessThan", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}.. 
        /// </summary>
        internal static string DataGrid_ValueMustBeLessThanOrEqualTo {
            get { 
                return ResourceManager.GetString("DataGrid_ValueMustBeLessThanOrEqualTo", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot throw null exception.. 
        /// </summary>
        internal static string DataGridDataErrorEventArgs_NullException {
            get { 
                return ResourceManager.GetString("DataGridDataErrorEventArgs_NullException", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Invalid row index. Cannot complete operation.. 
        /// </summary>
        internal static string DataGridRow_InvalidRowIndexCannotCompleteOperation {
            get { 
                return ResourceManager.GetString("DataGridRow_InvalidRowIndexCannotCompleteOperation", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Can only change SelectedItems collection in ExtendedFullRow selection mode.  Use SelectedItem property in SingleFullRow selection mode.. 
        /// </summary>
        internal static string DataGridSelectedItemsCollection_CannotChangeSelectedItemsCollectionInSingleMode {
            get { 
                return ResourceManager.GetString("DataGridSelectedItemsCollection_CannotChangeSelectedItemsCollectionInSingleMode", resourceCulture);
            }
        } 
    } 
}
