.TH "xamlg" 1
.SH NAME
respack \- Resource Packager
.SH SYNOPSIS
.B respack output.resource [files]
.SH DESCRIPTION
respack is a tool that wraps the input files in MemoryStreams and
saves them into the output.resource file.   This is used to package
one or more XAML files as a managed resource that gets embedded into
assemblies that are shipped inside a XAP file. 
.SH OPTIONS
.TP
.B -? | -help
Display information about respack
.PP
.SH COPYRIGHT
Copyright (C) 2008 Novell, Inc (http://www.novell.com)
.SH MAILING LISTS
Visit http://lists.ximian.com/mailman/listinfo/mono-devel-list for details.
.SH WEB SITE
Visit: http://www.mono-project.com for details
