// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Button button49;
    
    private Gtk.Entry entry2;
    
    private Gtk.Button button20;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Image image1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.button49 = new Gtk.Button();
        this.button49.CanFocus = true;
        this.button49.Name = "button49";
        this.button49.UseUnderline = true;
        this.button49.Label = Mono.Unix.Catalog.GetString("Load FIle");
        this.hbox2.Add(this.button49);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox2[this.button49]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.entry2 = new Gtk.Entry();
        this.entry2.CanFocus = true;
        this.entry2.Name = "entry2";
        this.entry2.IsEditable = true;
        this.entry2.InvisibleChar = '*';
        this.hbox2.Add(this.entry2);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.entry2]));
        w2.Position = 1;
        // Container child hbox2.Gtk.Box+BoxChild
        this.button20 = new Gtk.Button();
        this.button20.CanFocus = true;
        this.button20.Name = "button20";
        this.button20.UseUnderline = true;
        this.button20.Label = Mono.Unix.Catalog.GetString("Convert");
        this.hbox2.Add(this.button20);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.button20]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        this.vbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.image1 = new Gtk.Image();
        this.image1.Name = "image1";
        this.hbox1.Add(this.image1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.image1]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 504;
        this.DefaultHeight = 442;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button49.Clicked += new System.EventHandler(this.OnChooseFile);
        this.button20.Clicked += new System.EventHandler(this.OnConvert);
    }
}
