animation-recorder: animation-recorder.cpp
	gcc animation-recorder.cpp -o animation-recorder `pkg-config --libs --cflags gtk+-2.0 mozilla-gtkmozembed mozilla-js moon`

clean:
	rm -f animation-recorder
	rm -f *.png

