//------------------------------------------------------------------------------ 
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated> 
//-----------------------------------------------------------------------------
 
namespace System.Windows.Controls {
    using System;
 

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc. 
    /// </summary> 
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio. 
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /*[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")] */
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource { 
 
        private static global::System.Resources.ResourceManager resourceMan;
 
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] 
        internal Resource() {
        }
 
        /// <summary> 
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary> 
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get { 
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Controls.Resource", typeof(Resource).Assembly);
                    resourceMan = temp; 
                } 
                return resourceMan;
            } 
        }

        /// <summary> 
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary> 
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] 
        internal static global::System.Globalization.CultureInfo Culture {
            get { 
                return resourceCulture;
            }
            set { 
                resourceCulture = value;
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to ClickMode must be Release, Press, or Hover.. 
        /// </summary>
        internal static string ButtonBase_OnClickModePropertyChanged_InvalidValue {
            get { 
                return ResourceManager.GetString("ButtonBase_OnClickModePropertyChanged_InvalidValue", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to The name of the resource to load cannot be empty.. 
        /// </summary>
        internal static string Common_Extensions_LoadXamlResource_EmptyResourceName {
            get { 
                return ResourceManager.GetString("Common_Extensions_LoadXamlResource_EmptyResourceName", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to HasContent must correspond with the value of Content.. 
        /// </summary>
        internal static string ContentControl_HasContent_Inconsistent {
            get { 
                return ResourceManager.GetString("ContentControl_HasContent_Inconsistent", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to The template can only be applied one time.. 
        /// </summary>
        internal static string ContentPresenter_OnApplyTemplate_WriteOnce {
            get { 
                return ResourceManager.GetString("ContentPresenter_OnApplyTemplate_WriteOnce", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate to locations relative to the application when Application.Current has not been set.. 
        /// </summary>
        internal static string HyperlinkButton_GetAbsoluteUri_NoApplication {
            get { 
                return ResourceManager.GetString("HyperlinkButton_GetAbsoluteUri_NoApplication", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate to locations relative to a page.. 
        /// </summary>
        internal static string HyperlinkButton_GetAbsoluteUri_PageRelativeUri {
            get { 
                return ResourceManager.GetString("HyperlinkButton_GetAbsoluteUri_PageRelativeUri", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Failed to navigate to {0}.. 
        /// </summary>
        internal static string HyperlinkButton_Navigate_Failed {
            get { 
                return ResourceManager.GetString("HyperlinkButton_Navigate_Failed", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to IsSelectionActive is a read-only DependencyProperty.. 
        /// </summary>
        internal static string ListBox_OnIsSelectionActiveChanged_ReadOnly {
            get { 
                return ResourceManager.GetString("ListBox_OnIsSelectionActiveChanged_ReadOnly", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to FrameworkElement.Style property can be set only one time.. 
        /// </summary>
        internal static string ListBox_OnItemContainerStyleChanged_CanNotSetStyle {
            get { 
                return ResourceManager.GetString("ListBox_OnItemContainerStyleChanged_CanNotSetStyle", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to SelectedItems is a read-only DependencyProperty.. 
        /// </summary>
        internal static string ListBox_OnSelectedItemsChanged_ReadOnly {
            get { 
                return ResourceManager.GetString("ListBox_OnSelectedItemsChanged_ReadOnly", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Can only change the SelectedItems collection in multiple selection mode. Use SelectedItem in single selection mode.. 
        /// </summary>
        internal static string ListBox_OnSelectedItemsCollectionChanged_WrongMode {
            get { 
                return ResourceManager.GetString("ListBox_OnSelectedItemsCollectionChanged_WrongMode", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Only SelectionMode.Single is supported.. 
        /// </summary>
        internal static string ListBox_OnSelectionModeChanged_OnlySingleSelection {
            get { 
                return ResourceManager.GetString("ListBox_OnSelectionModeChanged_OnlySingleSelection", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be negative, infinite, or NaN.. 
        /// </summary>
        internal static string RangeBase_InvalidChangeValue {
            get { 
                return ResourceManager.GetString("RangeBase_InvalidChangeValue", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be infinite or NaN.. 
        /// </summary>
        internal static string RangeBase_InvalidDoubleValue {
            get { 
                return ResourceManager.GetString("RangeBase_InvalidDoubleValue", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Delay cannot be a negative value.. 
        /// </summary>
        internal static string RepeatButton_DelayPropertyCannotBeNegative {
            get { 
                return ResourceManager.GetString("RepeatButton_DelayPropertyCannotBeNegative", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Interval cannot be negative or zero.. 
        /// </summary>
        internal static string RepeatButton_IntervalMustBePositive {
            get { 
                return ResourceManager.GetString("RepeatButton_IntervalMustBePositive", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Unable to set a read-only DependencyProperty.. 
        /// </summary>
        internal static string ScrollViewer_OnReadOnlyDependencyPropertyChanged_ReadOnly {
            get { 
                return ResourceManager.GetString("ScrollViewer_OnReadOnlyDependencyPropertyChanged_ReadOnly", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} Content:{1} IsChecked:{2}. 
        /// </summary>
        internal static string ToggleButton_ToString_FormatString {
            get { 
                return ResourceManager.GetString("ToggleButton_ToString_FormatString", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to .... 
        /// </summary>
        internal static string ToolTip_PerformClipping_Ellipsis {
            get { 
                return ResourceManager.GetString("ToolTip_PerformClipping_Ellipsis", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Value must be positive.. 
        /// </summary>
        internal static string ToolTipService_SetTimeoutProperty_InvalidValue {
            get { 
                return ResourceManager.GetString("ToolTipService_SetTimeoutProperty_InvalidValue", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot convert from {1}.. 
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvert {
            get { 
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvert", resourceCulture);
            }
        } 
 
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert {1} to type {0}.. 
        /// </summary>
        internal static string TypeConverters_ConvertFromString_CannotConvert {
            get { 
                return ResourceManager.GetString("TypeConverters_ConvertFromString_CannotConvert", resourceCulture);
            }
        } 
    } 
}
