
SOURCES = \
    UnitTestHarness/AsynchronousAttribute.cs\
    UnitTestHarness/BugAttribute.cs\
    UnitTestHarness/CodeCoverage.cs\
    UnitTestHarness/CustomFrameworkUnitTest.cs\
    UnitTestHarness/Harness/Service/CodeCoverageProvider.cs\
    UnitTestHarness/Harness/Service/EnvironmentProvider.cs\
    UnitTestHarness/Harness/Service/Extensions.cs\
    UnitTestHarness/Harness/Service/IsolatedStorageSettingsProvider.cs\
    UnitTestHarness/Harness/Service/ProviderBase.cs\
    UnitTestHarness/Harness/Service/ServiceResult.cs\
    UnitTestHarness/Harness/Service/ServiceType.cs\
    UnitTestHarness/Harness/Service/SettingsProvider.cs\
    UnitTestHarness/Harness/Service/SilverlightTestService.cs\
    UnitTestHarness/Harness/Service/SilverlightTestService.ServiceVerifier.cs\
    UnitTestHarness/Harness/Service/TestReportingProvider.cs\
    UnitTestHarness/Harness/Service/TestServiceFeature.cs\
    UnitTestHarness/Harness/Service/WebCodeCoverageProvider.cs\
    UnitTestHarness/Harness/Service/WebEnvironmentProvider.cs\
    UnitTestHarness/Harness/Service/WebServiceResult.cs\
    UnitTestHarness/Harness/Service/WebSettingsProvider.cs\
    UnitTestHarness/Harness/Service/WebTestReportingProvider.cs\
    UnitTestHarness/Harness/Service/WebTestService.CrossThreadState.cs\
    UnitTestHarness/Harness/Service/WebTestService.cs\
    UnitTestHarness/Harness/Service/WebTestService.RequestData.cs\
    UnitTestHarness/Harness/TestServiceProvider.cs\
    UnitTestHarness/TagAttribute.cs\
    UnitTestHarness/UnitTesting/Harness/HarnessExtensions.cs\
    UnitTestHarness/UnitTesting/Harness/IProvideDynamicTestMethods.cs\
    UnitTestHarness/UnitTesting/Harness/RetryTestRunFilter.cs\
    UnitTestHarness/UnitTesting/Harness/TagManager.cs\
    UnitTestHarness/UnitTesting/Harness/TagManager.ExpressionEvaluator.cs\
    UnitTestHarness/UnitTesting/Harness/TagManager.Tags.cs\
    UnitTestHarness/UnitTesting/Harness/TagTestRunFilter.cs\
    UnitTestHarness/UnitTesting/Harness/TestAssemblyHelper.cs\
    UnitTestHarness/UnitTesting/Harness/TestClassHelper.cs\
    UnitTestHarness/UnitTesting/Harness/TestMethodHelper.cs\
    UnitTestHarness/UnitTesting/Harness/TestMethodManager.Silverlight.cs\
    UnitTestHarness/UnitTesting/Harness/TestRunFilter.cs\
    UnitTestHarness/UnitTesting/Harness/UnitTestLogicFactory.cs\
    UnitTestHarness/UnitTesting/Harness/VisualStudioLogProvider.cs\
    UnitTestHarness/UnitTesting/Harness/VisualStudioLogProvider.Writer.cs\
    UnitTestHarness/UnitTesting/UI/TextFailuresLogProvider.cs\
    UnitTestHarness/UnitTesting/UI/BrowserInformation.cs\
    UnitTestHarness/UnitTesting/UI/HtmlPropertyGrid.cs\
    UnitTestHarness/UnitTesting/UI/ResultInspector.Details.cs\
    UnitTestHarness/UnitTesting/UI/ResultInspector.cs\
    UnitTestHarness/UnitTesting/UI/ResultInspector.ExceptionDetails.cs\
    UnitTestHarness/UnitTesting/UI/TestPage.xaml.cs\
    UnitTestHarness/UnitTesting/UI/TestRunProgress.cs\
    UnitTestHarness/Properties/UnitTestMessage.Designer.cs\
    UnitTestHarness/UnitTestSystem.Silverlight.cs\
    UnitTestHarness/WorkItemTest.cs\
    UnitTestHarness/ExclusiveAttribute.cs\
    UnitTestHarness/GlobalSuppressions.cs\
    UnitTestHarness/IWorkItem.cs\
    UnitTestHarness/PresentationTest.cs\
    UnitTestHarness/SilverlightTest.cs\
    UnitTestHarness/WorkItem.cs\
    UnitTestHarness/UnitTesting/Harness/UnitTestLogMessageWriter.cs\
    UnitTestHarness/UnitTesting/Harness/UnitTestHarness.cs\
    UnitTestHarness/UnitTesting/Harness/UnitTestLogDecorator.cs\
    UnitTestHarness/UnitTesting/Harness/UnitTestMessageConditional.cs\
    UnitTestHarness/UnitTesting/Harness/LazyMethodAssemblyInfo.cs\
    UnitTestHarness/UnitTesting/Metadata/IAssembly.cs\
    UnitTestHarness/UnitTesting/Metadata/IExpectedException.cs\
    UnitTestHarness/UnitTesting/Metadata/IHostType.cs\
    UnitTestHarness/UnitTesting/Metadata/IPriority.cs\
    UnitTestHarness/UnitTesting/Metadata/ITestClass.cs\
    UnitTestHarness/UnitTesting/Metadata/ITestMethod.cs\
    UnitTestHarness/UnitTesting/Metadata/ITestProperty.cs\
    UnitTestHarness/UnitTesting/Metadata/IUnitTestProvider.cs\
    UnitTestHarness/UnitTesting/Metadata/IWorkItemMetadata.cs\
    UnitTestHarness/UnitTesting/Metadata/StringEventArgs.cs\
    UnitTestHarness/UnitTesting/Metadata/UnitTestProviderCapabilities.cs\
    UnitTestHarness/UnitTesting/SleepWorkItem.cs\
    UnitTestHarness/UnitTesting/UI/BrowserUtility.cs\
    UnitTestHarness/UnitTesting/UI/FailureEntry.cs\
    UnitTestHarness/UnitTesting/UI/FailureSummaryControl.cs\
    UnitTestHarness/UnitTesting/UI/TestHtmlElementManager.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/ExpectedException.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/Priority.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/ProviderAttributes.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/TestClass.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/TestMethod.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/TestProperty.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/UnitTestContext.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/UnitTestFrameworkAssembly.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/VsttProvider.cs\
    UnitTestHarness/UnitTesting/Metadata/VisualStudio/WorkItemMetadata.cs\
    UnitTestHarness/UnitTesting/UI/FailureControl.cs\
    UnitTestHarness/UnitTestSystem.cs\
    UnitTestHarness/Properties/AssemblyInfo.cs\
    UnitTestHarness/UnitTestSettings.cs\
    UnitTestHarness/UnitTesting/UI/CurrentTestStatus.cs\
    UnitTestHarness/UnitTesting/UI/TestPanelManager.cs\
    UnitTestHarness/UnitTesting/UI/UnitTestWebpageLog.cs\
    UnitTestHarness/UnitTesting/Harness/ScenarioResult.cs\
    UnitTestHarness/UnitTesting/Harness/AssemblyManager.cs\
    UnitTestHarness/UnitTesting/ICompositeWorkItem.cs\
    UnitTestHarness/UnitTesting/Harness/LazyMethodInfo.cs\
    UnitTestHarness/UnitTesting/Harness/MethodContainer.cs\
    UnitTestHarness/UnitTesting/Harness/TestClassInstanceDictionary.cs\
    UnitTestHarness/UnitTesting/Harness/TestClassManager.cs\
    UnitTestHarness/UnitTesting/WorkItemsManager.cs\
    UnitTestHarness/UnitTesting/Harness/TestMethodManager.cs\
    UnitTestHarness/UnitTesting/CompositeWorkItem.cs\
    UnitTestHarness/UnitTesting/Harness/UnitTestMethodContainer.cs\
    UnitTestHarness/UnitTesting/Harness/UnitTestCompositeWorkItem.cs\
    UnitTestHarness/UnitTesting/CallbackWorkItem.cs\
    UnitTestHarness/UnitTesting/ConditionalWorkItem.cs\
    UnitTestHarness/UnitTesting/MethodInvokeWorkItem.cs\
    UnitTestHarness/UnitTesting/Metadata/UnitTestProviders.cs\
    UnitTestHarness/Harness/DecoratorDictionary.cs\
    UnitTestHarness/Harness/ResourceUtility.cs\
    UnitTestHarness/Harness/LogMessageFactory.cs\
    UnitTestHarness/Harness/LogMessageWriter.cs\
    UnitTestHarness/Harness/LogDecorator.cs\
    UnitTestHarness/Harness/TestOutcome.cs\
    UnitTestHarness/Harness/TestStage.cs\
    UnitTestHarness/Harness/LogProvider.cs\
    UnitTestHarness/Harness/TestHarness.cs\
    UnitTestHarness/Harness/GlobalExceptionHandler.cs\
    UnitTestHarness/Harness/LogMessage.cs\
    UnitTestHarness/Harness/TestGranularity.cs\
    UnitTestHarness/Harness/DebugOutputProvider.cs\
    UnitTestHarness/Harness/ITestHarness.cs\
    UnitTestHarness/Harness/LogMessageType.cs\
    UnitTestHarness/Harness/ITestSettingsLogProvider.cs\
    UnitTestHarness/UI/WebpageHeaderLogProvider.cs\
    UnitTestHarness/UI/WebpageLogProvider.cs\
    UnitTestHarness/UI/WebpageLogProviderBase.cs\
    UnitTestHarness/Harness/TestHarnessCompletedEventArgs.cs\
    UnitTestHarness/Harness/RunDispatcher.cs\
    UnitTestHarness/Harness/TestHarnessSettings.cs\
    UnitTestHarness/UI/HtmlTestColumn.cs\
    UnitTestHarness/Html/CssPosition.cs\
    UnitTestHarness/Html/EventAttachment.cs\
    UnitTestHarness/Html/HtmlControlBase.cs\
    UnitTestHarness/Html/BorderStyle.cs\
    UnitTestHarness/Html/CssDisplay.cs\
    UnitTestHarness/Html/CssSize.cs\
    UnitTestHarness/Html/CssAttribute.cs\
    UnitTestHarness/Html/CssMargin.cs\
    UnitTestHarness/Html/CssPadding.cs\
    UnitTestHarness/Html/CssBox.cs\
    UnitTestHarness/Html/FontInfo.cs\
    UnitTestHarness/Html/FontNamesConverter.cs\
    UnitTestHarness/Html/FontSize.cs\
    UnitTestHarness/Html/FontUnit.cs\
    UnitTestHarness/Html/FontUnitConverter.cs\
    UnitTestHarness/Html/HtmlAnchor.cs\
    UnitTestHarness/Html/HtmlAttribute.cs\
    UnitTestHarness/Html/HtmlButton.cs\
    UnitTestHarness/Html/HtmlContainerControl.cs\
    UnitTestHarness/Html/HtmlControlCollection.cs\
    UnitTestHarness/Html/HtmlControlManager.cs\
    UnitTestHarness/Html/HtmlDiv.cs\
    UnitTestHarness/Html/HtmlElementWrapperBag.cs\
    UnitTestHarness/Html/HtmlElementWrapper.cs\
    UnitTestHarness/Html/HtmlEvent.cs\
    UnitTestHarness/Html/HtmlHeaderControl.cs\
    UnitTestHarness/Html/HtmlInputControl.cs\
    UnitTestHarness/Html/HtmlInputText.cs\
    UnitTestHarness/Html/HtmlLineBreak.cs\
    UnitTestHarness/Html/HtmlPageControl.cs\
    UnitTestHarness/Html/HtmlProperty.cs\
    UnitTestHarness/Html/Box.cs\
    UnitTestHarness/Html/CssBorder.cs\
    UnitTestHarness/Html/HtmlControl.cs\
    UnitTestHarness/Html/Extensions.cs\
    UnitTestHarness/Html/HtmlSpan.cs\
    UnitTestHarness/Html/HtmlTag.cs\
    UnitTestHarness/UI/Color.cs\
    UnitTestHarness/Html/BrowserScreenInformation.cs\
    UnitTestHarness/Html/Paragraph.cs\
    UnitTestHarness/Html/Size.cs\
    UnitTestHarness/Html/StyleProvider.cs\
    UnitTestHarness/Html/Unit.cs\
    UnitTestHarness/Html/UnitConverter.cs\
    UnitTestHarness/Html/UnitType.cs\
    UnitTestHarness/UI/ResultIndicatorColor.cs\
    UnitTestHarness/UI/TestColumnHeader.cs\
    UnitTestHarness/UI/TestStyleProvider.cs\
    UnitTestHarness/UI/WebBrowserTestPage.cs\
    UnitTestHarness/UI/WebBrowserTick.cs\
    UnitTestHarness/Harness/TestHarnessState.cs\
    UnitTestHarness/Harness/ReflectionUtility.cs\
    UnitTestHarness/UnitTesting/UI/TestPage.xaml.g.cs

RESOURCES = \
    -res:UnitTestHarness/Properties/UnitTestMessage.resources,Microsoft.Silverlight.Testing.Properties.UnitTestMessage.resources

REFERENCES = \
	-r:System \
	-r:System.Net \
	-r:System.Xml \
	-r:System.Xml.Linq \
	-r:System.Core \
	-r:Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight.dll


default: Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight.dll resources
	smcs $(SOURCES) $(RESOURCES) $(REFERENCES) `pkg-config --libs silver` -noconfig -define:SILVERLIGHT,VISUALSTUDIO_SUPPORT -target:library -out:Microsoft.Silverlight.Testing.dll -debug:full


resources: UnitTestHarness/Properties/UnitTestMessage.resx
	resgen2 UnitTestHarness/Properties/UnitTestMessage.resx

Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight.dll: 
	cd ../Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight/ && $(MAKE)
	cp ../Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight/Microsoft.VisualStudio.QualityTools.UnitTesting.Silverlight.dll .



