/* -*- Mode: C++; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * multiscalesubimage.cpp
 *
 * Contact:
 *   Moonlight List (moonlight-list@lists.ximian.com)
 *
 * Copyright 2007-2008 Novell, Inc. (http://www.novell.com)
 *
 * See the LICENSE file included with the distribution for details.
 * 
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <glib.h>

#include "debug.h"
#include "runtime.h"
#include "deepzoomimagetilesource.h"
#include "multiscalesubimage.h"

MultiScaleSubImage::MultiScaleSubImage ()
{
	SetObjectType (Type::MULTISCALESUBIMAGE);
	source = NULL;	
	parent = NULL;
}

MultiScaleSubImage::MultiScaleSubImage (Uri *parent_uri, MultiScaleTileSource *tsource, int _id, int _n)
{
	LOG_MSI ("new MultiScaleSubImage ()\n");
	SetObjectType (Type::MULTISCALESUBIMAGE);
	source = tsource;
	parent = NULL;
	id = _id;
	n = _n;

	const char *sourceUriString = ((DeepZoomImageTileSource*)source)->GetUriSource() ? ((DeepZoomImageTileSource*)source)->GetUriSource()->GetOriginalString () : "";
	const char *parentUriString = parent_uri ? parent_uri->GetOriginalString () : "";
	
	//FIXME: for now I strip the latest part of parent_uri and concat the uri from tsource.
	//it seems to work for images generated by DeepZoom, but it's not bulletproof
	if (g_str_has_prefix (sourceUriString, "http://"))
		return;
	char buffer [strlen (parentUriString) + strlen (sourceUriString)+1];
	strcpy (buffer, parentUriString);
	char *p = g_strrstr (buffer, "/");
	if (!p)
		return;

	strcpy (p + 1, sourceUriString);
	LOG_MSI ("UriSource changed to %s (from %s)\n", buffer, sourceUriString);
	Uri *newSourceUri = new Uri ();

	if (newSourceUri->Parse (buffer))
		((DeepZoomImageTileSource*)source)->SetUriSource (newSourceUri);
	delete newSourceUri;
}

double
MultiScaleSubImage::GetViewportHeight ()
{
	return GetAspectRatio () * GetViewportWidth ();
}

void
MultiScaleSubImage::OnPropertyChanged (PropertyChangedEventArgs *args, MoonError *error)
{
	if (args->GetId () == MultiScaleSubImage::ViewportOriginProperty) {
		Point *p = args->new_value->AsPoint();
		if (parent)
			parent->Invalidate ();
	}

	if (args->GetId () == MultiScaleSubImage::ViewportWidthProperty) {
		if (parent)
			parent->Invalidate ();
	}

	if (args->GetProperty ()->GetOwnerType () != Type::MULTISCALESUBIMAGE) {
		DependencyObject::OnPropertyChanged (args, error);
		return;
	}
	
	NotifyListenersOfPropertyChange (args);
}
